apiVersion: v1
version: 0.1.0

name: istio
appVersion: 1.1.0
tillerVersion: ">=2.7.2-0"
description: A custom Istio chart, tailored for personal use.
keywords:
  - istio
  - security
  - sidecarInjectorWebhook
  - mixer
  - pilot
  - galley
sources:
  - http://github.com/istio/istio

engine: gotpl
icon: https://istio.io/favicons/android-192x192.png
