apiVersion: v1
appVersion: 1.2.5
description: A customized Helm chart of all Istio components.
engine: gotpl
icon: https://istio.io/favicons/android-192x192.png
keywords:
- istio
- security
- sidecarInjectorWebhook
- mixer
- pilot
- galley
name: istio
sources:
- http://github.com/istio/istio
tillerVersion: '>=2.7.2-0'
version: 1.2.5-custom-4
