apiVersion: v1
tillerVersion: '>=2.7.2'
version: 1.1.2-custom-1

name: gateways
appVersion: 1.1.2
description: Helm chart for deploying Istio gateways

sources: ["http://github.com/istio/istio"]
keywords:
- istio
- ingressgateway
- egressgateway
- gateways

engine: gotpl
icon: https://istio.io/favicons/android-192x192.png
